[package]
name = "commons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.6.1"
# mongod-derive = "0.3.3"
serde = { version = "1.0.137", features = ['derive'] }